version: 2.1

orbs:
  node: circleci/node@5.2.0
jobs:
  install-node-example:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run:
          name: Check linting
          command: npm run lint
workflows:
  test_my_app:
    jobs:
      - install-node-example