version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
       - node/install:
          node-version: "16.13"
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: npm run build
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: Deploy app
          command: echo 'Project is deployed'

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
