version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Check linting
          command: npm run lint
  test:
    executor: node/default
    steps:
      - run:
          name: Run tests
          command: npm run test
  build:
    executor: node/default
    steps:
      - run:
          name: Build app
          command: npm run build

  deploy:
    executor: node/default
    steps:
      - run:
          name: Deploy app
          command: echo 'App is deployed'

workflows:
  Build main branch:
    jobs:
      - lint
      - test
      - build
      - deploy:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only: main # only deploy when on main
